import { Brain, Mail, User, FileText } from "lucide-react";

const FeaturesSection = () => {
  const features = [
    {
      title: "Ask AI",
      subtitle: "AI that answers questions for you, real‑time",
      description: "Clarity uses the screen, transcript, and AI to answer questions for you, live.",
      icon: Brain,
    },
    {
      title: "Instant follow-up emails",
      description: "Send perfectly drafted follow-up emails within seconds after every call.",
      icon: Mail,
    },
    {
      title: "Who are you really talking to?",
      description: "Learn everything about anyone before every call — where they work, what they do, and more.",
      icon: User,
    },
    {
      title: "Beautiful meeting notes",
      subtitle: "Beautiful meeting notes",
      description: "Instant shareable meeting notes generated by AI.",
      icon: FileText,
    },
  ];

  return (
    <section id="features" className="py-20 md:py-32 px-4">
      <div className="container mx-auto max-w-7xl">
        {/* Section Header */}
        <div className="text-center mb-16 md:mb-24">
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-foreground">
            Four ways we make your<br />
            meetings better
          </h2>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-2 gap-8 md:gap-12">
          {features.map((feature, index) => {
            const IconComponent = feature.icon;
            return (
              <div key={index} className="space-y-4">
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0">
                    <IconComponent className="w-6 h-6 text-foreground" />
                  </div>
                  <div className="flex-1 space-y-2">
                    <h3 className="text-2xl md:text-3xl font-bold text-foreground">
                      {feature.title}
                    </h3>
                    {feature.subtitle && (
                      <p className="text-lg text-foreground/70">
                        {feature.subtitle}
                      </p>
                    )}
                    <p className="text-base text-foreground/60 leading-relaxed">
                      {feature.description}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
